{% set version = "0.0.2" %}

package:
  name: scitime
  version: {{ version }}

source:
  url: https://github.com/nathan-toubiana/scitime/archive/v{{ version }}.tar.gz
  sha256: 603fdf938159d0b8a1c52fb500cfa4ef7d237a314d438246ae23f2c21cd4f8c8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - setuptools >=3.3
    - pip
  run:
    - python >=3.6
    - psutil
    - joblib
    - scikit-learn
    - pandas

test:
  imports:
    - scitime

about:
  home: https://github.com/nathan-toubiana/scitime
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Training time estimation for scikit-learn algorithms'

  description: |
    Training time estimation for scikit-learn algorithms.
  dev_url: https://github.com/nathan-toubiana/scitime

extra:
  recipe-maintainers:
    - nathan-toubiana
