{% set version = "0.1.0" %}

package:
  name: scitime
  version: {{ version }}

source:
  url: https://github.com/scitime/scitime/archive/v{{ version }}.tar.gz
  sha256: 32319c106f1c7c026acd33d78f138cef2016b44cec20995ab5127edc6bb8f969

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - setuptools >=3.3
    - pip
  run:
    - python >=3.6
    - psutil
    - joblib
    - scikit-learn
    - pandas

test:
  imports:
    - scitime

about:
  home: https://github.com/scitime/scitime
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Training time estimation for scikit-learn algorithms'

  description: |
    Training time estimation for scikit-learn algorithms.
  dev_url: https://github.com/scitime/scitime

extra:
  recipe-maintainers:
    - nathan-toubiana
