{% set version = "0.1.0" %}

package:
  name: scitime
  version: {{ version }}

source:
  url: https://github.com/scitime/scitime/archive/v{{ version }}.tar.gz
  sha256: e846f360cd185902cc7b81a4f88921ec522d8c891bf04df316d7878aa4e9e504

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - setuptools >=3.3
    - pip ==20.3.4
  run:
    - python >=3.7
    - psutil
    - joblib
    - scikit-learn
    - pandas

test:
  imports:
    - scitime

about:
  home: https://github.com/scitime/scitime
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Training time estimation for scikit-learn algorithms'

  description: |
    Training time estimation for scikit-learn algorithms.
  dev_url: https://github.com/scitime/scitime

extra:
  recipe-maintainers:
    - nathan-toubiana
