travis:
  secure:
    BINSTAR_TOKEN: P2N6Sx2Vmw1z5IKAc2c6GzKwMm6nAmS0DMEPhcrgSEOY5or5Tasep7ja302KErUwRjBv8KG945I2UnWB/M43pSWt2c2+iYbhSQMyHlWu3kKbKgYaiIMfx34fatgEx5n6/++ledwaInVW9iFi39F8p+OBiY++uksJIyhdqZuLzV2zUSQf938GzEtD7A6n675d/AniLJimkkTxmU18SL1dHK9K3mFD3N64AFh/MVjQXaUfonRbIdkOCwP7O1TOrAtR0/tlh1YDkz87M4h1OQhKpiiSzx7VGCDBgUK6SkAHbqqgjhyYP7k3Y10HwEdf3lcJ9iKM3gA2APZRnRsmkpqeCLgSbPLSNRwMsfSfLB65AHaWa0H0tQ32XGnGzYrcnUVWd4JTq5bka+zJRDunGZ9wO4wxY64L02Dc97Yy8drVg+hsugBgSxZ6npwdkaMTobMMZvBeQ5TieTdPAT4vuAWNl/gO8oNTIPS4uqZ++BFf5aCHmKxZeQGCXyPZajSjzbEWn/ndmYYs0dICH2LlscxMia0mNbuhNDFTQUISeOQarXF8Wu8m5i0CvOycYexy8Gzm6431bkbqxJ5VT2qrpCALmTOeLZ+qIszKg5SicDrV0Tjj6Qo9/gW+nyaHXRdHfJr5VhICndHkpZLEw5h384g5yQ8Ess53Mp8y9PYRi8RUJxs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
